"""Decode candidate Stardew Valley BGM/ambient cues to web-friendly ogg files.

Inputs come from `wave_named/`, which was generated by unxwb -b. Some names may
be mis-mapped due to XSB ordering quirks; we still take the biggest candidates
and trust those whose name + size both make sense for the role.
"""
import os, subprocess, sys

VGM = r"C:\Users\zhong\Desktop\stardew-wrapped\.tools\vgm\vgmstream-cli.exe"
FFMPEG = r"C:\Users\zhong\Desktop\stardew-wrapped\.tools\ffmpeg\ffmpeg-8.1.1-essentials_build\bin\ffmpeg.exe"
SRC_DIR = r"C:\Users\zhong\Desktop\stardew-wrapped\.tools\unxwb\wave_named"
OUT_DIR = r"C:\Users\zhong\Desktop\stardew-wrapped\assets\audio"
TMP_DIR = r"C:\Users\zhong\Desktop\stardew-wrapped\.tools\pcm_tmp"

os.makedirs(OUT_DIR, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)

# (source basename in wave_named, target name, extra ffmpeg args for trimming/normalizing)
CANDIDATES = [
    ("title_night",        "bgm_title.ogg",   ["-q:a", "3"]),
    ("summer2",            "bgm_summer.ogg",  ["-q:a", "3"]),
    ("spring_day_ambient", "bgm_spring.ogg",  ["-q:a", "3"]),
    ("ocean",              "bgm_fall.ogg",    ["-q:a", "3"]),
    ("Majestic",           "bgm_winter.ogg",  ["-q:a", "3"]),
    ("thunder",            "amb_thunder.ogg", ["-q:a", "4"]),
    ("cricketsAmbient",    "amb_night.ogg",   ["-q:a", "4"]),
    ("waterfall",          "amb_water.ogg",   ["-q:a", "4"]),
    ("rainsound",          "amb_rain.ogg",    ["-q:a", "4"]),
    ("wind",               "amb_wind.ogg",    ["-q:a", "4"]),
]

for base, out, extra in CANDIDATES:
    src = os.path.join(SRC_DIR, base + ".wav")
    if not os.path.exists(src):
        print(f"[skip] missing {src}")
        continue
    pcm = os.path.join(TMP_DIR, base + ".pcm.wav")
    out_path = os.path.join(OUT_DIR, out)
    print(f"[decode] {base} -> pcm")
    r = subprocess.run([VGM, "-o", pcm, src], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"  vgm fail: {r.stderr[:300]}"); continue
    print(f"[encode] {pcm} -> {out_path}")
    r = subprocess.run([FFMPEG, "-y", "-hide_banner", "-loglevel", "error",
                        "-i", pcm, "-c:a", "libvorbis", "-ar", "44100"] + extra +
                       [out_path], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"  ffmpeg fail: {r.stderr[:300]}"); continue
    print(f"  ok size={os.path.getsize(out_path)}")

print("done")
